### ISSUE TITLE
Preferences window

### ISSUE THREAD

**Issue by jamieweavis** [jamiestraw/streaker#12]
Multiple options have been added to Streaker, and it now feels as if a Preferences window would be useful as a central place to manage them all to avoid adding too many options to the tray.

This new window would replace the existing username and notification pop-ups and act as more of a window rather than a pop-up.

We could get away with basic styling for the pop-ups but the Preferences window will require more user interface elements and will potentially include more options in the future, this seems like a good chance to incorporate a framework - [Bulma](https://github.com/jgthms/bulma) seems like it could be a good choice.

**Comment by KeziahMoselle** [comment]
If I let the username window is it okay ? Because I was thinking about the installation of Streaker when the installation is finished, we should launched the preferences window and focus the username input or launch the username window only at the first launch ?
What do you think ?

**Comment by jamieweavis** [comment]
Let's remove the username window and launch the Preferences window when the app is ready if the username is not set 👍

**Comment by jamieweavis** [comment]
For reference, this is being worked on in #13.

**Comment by jamieweavis** [comment]
Added in #13! 🎉
