### ISSUE TITLE
Add auto update functionality

### ISSUE THREAD

**Issue by jamieweavis** [jamiestraw/streaker#15]
As Streaker is becoming more feature rich it would be nice to add auto-update functionality so that users don't have to manually check and download new versions

**Comment by KeziahMoselle** [comment]
Do you plan to sign your app ?
Apparently it is needed for MacOS otherwise auto update won't work.
And it costs 99$/year

**Comment by jamieweavis** [comment]
I don't have an Apple developer membership and don't plan on buying one just for Streaker. I thought that automatic updating could be implemented on macOS with a self signed certificate?

**Comment by KeziahMoselle** [comment]
I don't know, it should work but it will still show the alert window doesn't it ?
I'm interested too, if you have the answser 😄

**Comment by jamieweavis** [comment]
I don't know, I can't seem to find much information about it. When I have time I will investigate and let you know 😄
