### ISSUE TITLE
does this track all commits, or only on main branch?

### ISSUE THREAD

**Issue by bnidevs** [jamiestraw/streaker#254]
just a quick question, will close when answered

**Comment by jamieweavis** [comment]
Hey, yeah that's right, Streaker is powered by your GitHub contribution graph at: https://github.com/users/bnidevs/contributions

Contributions are only counted from the default branch of your repositories, for more info on how contributions are counted see: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commits

**Comment by jamieweavis** [comment]
Hey @bnidevs, yeah that's right, Streaker is powered by your GitHub contribution graph at: https://github.com/users/bnidevs/contributions

Contributions are only counted from the default branch of your repositories, for more info on how contributions are counted see: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commits

**Comment by bnidevs** [comment]
got it thanks!
