### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by justin-schroeder** [jamiestraw/streaker#260]
👋 Love this app idea and I wish I had found it years ago. Definitely could help keep me motivated.

That said, it seems its not pulling any data from my account:

![image](https://user-images.githubusercontent.com/1950463/224769235-1fa3d7d5-9eeb-43f3-abef-79b013edd6f8.png)

Vs my actual graph:

![image](https://user-images.githubusercontent.com/1950463/224769315-d5342d14-9c4d-444b-9b2b-409f60c9714a.png)

Thoughts?

**Comment by jamieweavis** [comment]
Thanks for opening this issue @justin-schroeder!

GitHub recently (not sure when) changed the way that the https://github.com/users/jamieweavis/contributions page is structured which broke [the library](https://github.com/jamieweavis/contribution) that Streaker uses under the hood to fetch contribution data...

I've fixed this downstream in [v5.0.3](https://github.com/jamieweavis/contribution/releases/tag/v5.0.3), I just need to upgrade to the latest version here and then do a release which I'm hoping to do soon, hopefully I don't have any issues building the app on M1 architecture 🤞

**Comment by jamieweavis** [comment]
Fixed in https://github.com/jamieweavis/streaker/commit/8405c6e8db0bb73a56bb5e128233562fb95c5e96 and released in [v1.5.1](https://github.com/jamieweavis/streaker/releases/tag/v1.5.1), thanks for your interest in the project! 🙏
