### ISSUE TITLE
Uncaught Exception on Connection Loss

### ISSUE THREAD

**Issue by yursky** [jamiestraw/streaker#7]
Losing a socket connection is not handled gracefully. A large notification window is displayed across the screen. 

I think should either be a silent error or a unique state the application can enter. I can potentially take a look at this later once I have some free time.

<img width="417" alt="socket_hangup" src="https://user-images.githubusercontent.com/6846386/45525009-0c05af80-b786-11e8-979b-8f76209985b8.png">

**Comment by yursky** [comment]
This happens to me every day when my train goes through the SF Bay Tunnel 😛

**Comment by jamieweavis** [comment]
I've never came across this issue myself, but you're right - this is a terrible UX! I'll look at getting your PR merged within the next few days, thanks 👍

**Comment by jamieweavis** [comment]
Resolved in #8.
